export const NAVIGATION = {
  public: [
    { label: "Accueil", href: "/" },
    { label: "Ingénierie", href: "/ingenierie" },
    { label: "Ébénisterie", href: "/ebenisterie" },
    { label: "Plans", href: "/plans" },
    { label: "Immobilier", href: "/immobilier" },
    { label: "Portfolio", href: "/portfolio" },
    { label: "À propos", href: "/a-propos" },
    { label: "Blog", href: "/blog" },
    { label: "Contact", href: "/contact" },
  ],
  client: [
    { label: "Dashboard", href: "/compte" },
    { label: "Mon chantier", href: "/compte/chantier" },
    { label: "Commandes", href: "/compte/commandes" },
    { label: "Factures", href: "/compte/factures" },
    { label: "Plans", href: "/compte/plans" },
    { label: "Profil", href: "/compte/profil" },
  ],
  gestion: [
    { label: "Dashboard", href: "/gestion" },
    { label: "Planning", href: "/gestion/planning" },
    { label: "Rapports", href: "/gestion/rapports" },
    { label: "Approvisionnements", href: "/gestion/approvisionnements" },
    { label: "Équipes", href: "/gestion/equipes" },
    { label: "HSE", href: "/gestion/hse" },
    { label: "Documents", href: "/gestion/documents" },
  ],
  admin: [
    { label: "Dashboard", href: "/admin" },
    { label: "Plans", href: "/admin/plans" },
    { label: "Produits", href: "/admin/produits" },
    { label: "Biens", href: "/admin/biens" },
    { label: "Commandes", href: "/admin/commandes" },
    { label: "Chantiers", href: "/admin/chantiers" },
    { label: "Clients", href: "/admin/clients" },
    { label: "Leads", href: "/admin/leads" },
    { label: "Contenu", href: "/admin/contenu" },
    { label: "Paramètres", href: "/admin/parametres" },
  ],
} as const;
